### PR TITLE
Fix for broken newListener option

### PR DESCRIPTION
**Pull request by ColonelBundy**
setting newListener to false didn't do anything and this was the cause.

UPDATE: Second commit is merely to have a truly quiet emitter which I desperately need :)

### CODE REVIEW

**Comment by RangerMauve** [comment]
Hi, thanks for the PR! Next time it would be nice if you could include the second commit as part of a separate PR. Could you please add some unit tests for these features?

**Comment by fmassicano** [comment]
Please, I need this feature committed to the master.

**Comment by RangerMauve** [comment]
Fair enough, I'll merge it in.

**Comment by RangerMauve** [comment]
Oh jeeze, this PR broke the `emitter.removeListener()` function. Please make sure to run `npm run test` before submitting PRs! Also my bad for not testing it first, I'll be more careful

**Comment by RangerMauve** [comment]
Released in 5.0.0 because this is an API breaking change.

**Pull request merged**
