### PR TITLE
Consistently export the EventEmitter

### PR DESCRIPTION
**Pull request by kmalakoff**
Fixes: https://github.com/asyncly/EventEmitter2/issues/146

### CODE REVIEW

**Comment by larkin** [comment]
This fixes an issue which itself is a duplicate of https://github.com/asyncly/EventEmitter2/issues/121.  That issue has it's own pull request (https://github.com/asyncly/EventEmitter2/pull/122) which implements exactly the same solution.

Is there any reason why this pull request (or alternatively, https://github.com/asyncly/EventEmitter2/pull/122) has not been merged?

If you create a package that depends on eventemitter2 and use commonjs module loading, anyone who uses requirejs will be unable to use your package unless you create a workaround, such as the one visible here: https://github.com/bbcrd/peaks.js/pull/79/files.

Is there anything I can do to help get this PR merged?

**Comment by kmalakoff** [comment]
@larkin I gave up on this library due to inactivity. I'm using this now: https://github.com/primus/eventemitter3

**Comment by 0x00A** [comment]
@larkin The only reason that it hasn't been merged is that there are no maintainers. Would you like maintainer access?

**Comment by RangerMauve** [comment]
I'd be interested in doing more active maintenance, but I don't have NPM publish rights so I can't really do much.

**Comment by 0x00A** [comment]
@RangerMauve :sparkles: added you on npm :sparkles:

**Comment by 0x00A** [comment]
also +1 on this PR

**Comment by RangerMauve** [comment]
Cool, I'll have some time later tonight to work with this. I'm thinking I'll look at some of the smaller PRs first and consider this more of a major bump.

**Comment by larkin** [comment]
@rangermauve awesome, thanks! Are you planning on doing a version bump (that includes this) soon?

**Comment by RangerMauve** [comment]
I've been super busy lately, but hopefully I'll get around to it this weekend or early next week. :D

**Comment by RangerMauve** [comment]
1.0.0 has been released with this change within it.

**Pull request merged**
