### PR TITLE
add an 'event' argument to onAny handlers

### PR DESCRIPTION
**Pull request by fresheneesz**
https://github.com/asyncly/EventEmitter2/issues/139

### CODE REVIEW

**Comment by hij1nx** [comment]
This looks good, i wonder what it would break though in existing code if suddenly the first value was the event.

**Comment by fresheneesz** [comment]
It certainly would, I assumed you knew that before you gave me the go ahead. Up the major version?

**Comment by hij1nx** [comment]
Yeah. But honestly my head is not in this project. What about an option for this behavior so we don't break anything?

**Comment by hij1nx** [comment]
Also, would you be interested in becoming a maintainer on this project?

**Comment by RangerMauve** [comment]
Any chance I could become a maintainer? :3

**Comment by hij1nx** [comment]
@RangerMauve /cc @cxreg

**Comment by fresheneesz** [comment]
Well, I'm of the opinion that an improved API is worth breaking changes. Also, an option would be super confusing to people I think. If it were me, i'd just up the major version.

Also, I'm not actually gonna use this library. I wrote my own small extension of EventEmitter that has the `ifon` and a `proxy` method for proxying event listener attachment for performant event proxying. The code is here and I'll probably move it to its own project at some point: https://github.com/Tixit/blocks.js/blob/master/src/node_modules/EventEmitterB.js . But in any case, that means I have no motivation to maintain this project. Sorry!

**Comment by RangerMauve** [comment]
I agree with adding an option for enabling this feature, or maybe having it enable the old behavior to make it easier to transition.

**Comment by RangerMauve** [comment]
As was mentioned in #131, you should move the concatenation outside the for loop for better performance.

**Comment by jessedijkstra** [comment]
Rather use this.event instead of upping the major version for now.

Would indeed like this see the major be bumped for a proper onAny method.

Bumping a major would be a good idea anyways with the dependency problems created by the current UMD implementation.

**Comment by RangerMauve** [comment]
Gonna be adding a bunch of changes in at once as part of a major relase in the near future. Just gonna merge a bunch of stuff and work on the docs

**Comment by RangerMauve** [comment]
This has been released in 1.0.0

**Pull request merged**
