### PR TITLE
Sync library version aming files

### PR DESCRIPTION
**Pull request by kwiateusz**

### CODE REVIEW

**Comment by RangerMauve** [comment]
Thanks for the PR! Haven't been using bower or component anymore so it totally slipped my mind.

**Comment by kwiateusz** [comment]
@RangerMauve can you create tag 2.1.3 from actual master? Because afaik it depends on git tags when resolving.

**Comment by RangerMauve** [comment]
Done

**Comment by kwiateusz** [comment]
Thanks

**Pull request merged**
