### PR TITLE
Event listeners not added when delimiter at the start

### PR DESCRIPTION
**Pull request by ash-developer**
does't work for { wildcard: true }

### CODE REVIEW

**Comment by RangerMauve** [comment]
Do you think you could add a unit test that explicitly tests delimiters being at the start?

**Comment by ash-developer** [comment]
yes, sure
should do it early

also the same situation is appear for such message "asd.qwe." when delimeter is in the end
should eventemitter works for it?

**Comment by RangerMauve** [comment]
Personally, I wasn't around when that part was being introduced. I actually had these issues about a year or two ago, but ended up not needing to have wildcards at the start after all. If you could figure out how to make it work with having the delimiter at the end, I'm sure that'll be useful to people.

**Comment by RangerMauve** [comment]
Awesome, thanks for the PR

**Pull request merged**
